src/BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.IO;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        IUnitOfWork unitOfWork;
        IWebHostEnvironment webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            this.unitOfWork = unitOfWork;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> list = unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return View(list);
        }

        public IActionResult Upsert(int? id)
        {
            
            IEnumerable<SelectListItem> categoryList = unitOfWork.Category.GetAll().Select(u => new SelectListItem() { Text = u.Name, Value = u.Id.ToString() });
            // ViewBag.Category = categoryList;
            //ViewData["Category"] = categoryList;
            ProductVM productVM = new ProductVM()
            {
                CategoryList = categoryList
            };
            if (id == null || id == 0)
            {
                productVM.Product = new Product();

            }
            else
            {

                productVM.Product = unitOfWork.Product.Get(u => u.Id == id);
            }
            return View(productVM);
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM obj,IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string rootpath = webHostEnvironment.WebRootPath;

                if (!string.IsNullOrEmpty(obj.Product.ImageUrl))
                {
                    
                    var path = Path.Combine(rootpath , obj.Product.ImageUrl.TrimStart('\\'));
                    if(System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }                  

                }
                if (file != null)
                {

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    var productPath = Path.Combine(rootpath, @"images\product");
                    using (var filestream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    obj.Product.ImageUrl = @"\images\product\" + fileName;
                }
                if (obj.Product.ImageUrl == null ) 
                    obj.Product.ImageUrl = string.Empty;

                if (obj.Product.Id == 0)
                {

                    unitOfWork.Product.Add(obj.Product);
                }else
                {
                    unitOfWork.Product.Update(obj.Product);
                }
                unitOfWork.Save();
                TempData["Success"] = "Product Created Successfully";
                return RedirectToAction("Index");
            }
            else
            {
                obj.CategoryList = unitOfWork.Category.GetAll().Select(u => new SelectListItem() { Text = u.Name, Value = u.Id.ToString() });
                return View(obj);
            }
           

        }

        



      

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var obj = unitOfWork.Product.Get(u => u.Id == id);
            if (obj != null)
            {
                unitOfWork.Product.Remove(obj);
                unitOfWork.Save();
                TempData["success"] = "Record deleted successfully";
                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }

        }



        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var Product = unitOfWork.Product.Get(u => u.Id == id);
            if (Product == null)
            {
                return NotFound();
            }

            return View(Product);

        }

        public IActionResult GetAllData()
        {
            List<Product> list = unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = list });
        }
    }
}

src/BulkyWeb/Areas/Admin/Controllers/VendorController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VendorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public VendorController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Vendor> objVendorList = _unitOfWork.Vendor.GetAll().ToList();
            return View(objVendorList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Vendor.Add(vendor);
                _unitOfWork.Save();
                TempData["success"] = "Vendor created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var vendor = _unitOfWork.Vendor.Get(u => u.Id == id);
            if (vendor == null)
                return NotFound();

            return View(vendor);
        }

        [HttpPost]
        public IActionResult Edit(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Vendor.Update(vendor);
                _unitOfWork.Save();
                TempData["success"] = "Vendor updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var vendor = _unitOfWork.Vendor.Get(u => u.Id == id);
            if (vendor == null)
                return NotFound();

            return View(vendor);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.Vendor.Get(u => u.Id == id);
            if (obj == null)
                return NotFound();

            _unitOfWork.Vendor.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Vendor deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

src/BulkyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />   
    <link rel="stylesheet" href="~/BulkyBook.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.5/css/dataTables.dataTables.min.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Mangement
                            </a>
                            <ul class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <li><hr class="dropdown-divider"></li>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Vendor Management
                            </a>
                            <ul class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Vendor" asp-action="Index">Vendor Address</a>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_SharedMessages" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i>
            &copy; 2024 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.tiny.cloud/1/f2pcefo722y7900i01s5c7utlh6nnzwat7l07fsca2r9u6fw/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/2.0.5/js/dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/BulkyWeb/Views/Shared/_SharedMessages.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]')</script>
}
@if (TempData["error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">toastr.error('@TempData["error"]')</script>
}